### ISSUE TITLE
WARNING: when building desktop

### ISSUE THREAD

**Issue by 0XDE57** [0XDE57/SpaceProject#1]
Receive the following warning when building / launching desktop build. Unsure of cause...but project runs fine.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (...gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by TheFlemoid** [comment]
Just so you know, that's perfectly normal.  Gradle has hopes of removing reflective access in the future, and the LWJGL hooks that Gradle uses relies on reflective access for some stuff.  The warning is basically just saying "this may not work with a future version of Gradle", but the thing that may not work has nothing to do with your code, but rather it is OpenGL bindings that the framework is using.

**Comment by 0XDE57** [comment]
Oh, thanks. So I don't have to worry about it then?

I might bump up to LWJGL 3 in the future. Not sure if I should now or if it matters. But if I did would that give me any issues with bindings?

https://libgdx.com/news/2021/07/devlog-7-lwjgl3

**Comment by TheFlemoid** [comment]
Yep, nothing to worry about.  You should be able to bump to LWJGL3 just fine as well, shouldn't cause any problems.  Bumping to LWJGL3 is actually super easy following that tutorial you linked.  If you're working on Windows or Linux, you just have to modify your root build.gradle file to pull in the new dependency, and modify your DesktopLauncher to use the new dependency.

**Comment by 0XDE57** [comment]
Closing. Updated to to latest: https://github.com/0XDE57/SpaceProject/commit/400467f9ded8f5d49c3868ef4a9eb0028c5468fe
