### ISSUE TITLE
uknown crash on first couple runs on new machine

### ISSUE THREAD

**Issue by 0XDE57** [0XDE57/SpaceProject#24]
a play tester notified me of crash on their machine. trying to get logs
unable to repro on my machine.

**Comment by M0yma** [comment]
Here's the log

java -jar "C:\Users\user\Downloads\spaceproject_devember_enginedemo_20230131.jar"
[TitleScreen] ScreenAdapter Reset.
[TitleScreen] vsync = false
[NoiseAnim] density: 0.680737
[NoiseAnim] density: 0.680737
[TitleScreen] resize: 1280, 720
[TitleScreen] resize: 1280, 720
[GameScreen] ScreenAdapter Reset.
[GameScreen] vsync = true
[PhysicsDebug] 5772.0 K = 502.0 nm
[PhysicsDebug] 502.0 nm = 5772.5 K
[PhysicsDebug] temp(wave(5772.0)) = 5772.0
[PhysicsDebug] wave(temp(502.0)) = 502.0
[PhysicsDebug] 502.0 nm = 597.2 THz
[PhysicsDebug] wavelength expected: true
[PhysicsDebug] temperature expected: true
[PhysicsDebug] planck double: 6.626E-34
[PhysicsDebug] size of double: [4.9E-324 to 1.7976931348623157E308] exp: [-1022 to 1023]
[PhysicsDebug] planck bigdecimal: 6.62607015E-34 -> 0.000000000000000000000000000000000662607015 | precision: 9  - scale: 42
[PhysicsDebug] h * c def:  0.000000000000000000000000198644586 | precision: 9  - scale: 33
[PhysicsDebug] h * c calc: 1.98644585714892870E-25 -> 0.000000000000000000000000198644585714892870 | precision: 18  - scale: 42
[PhysicsDebug] 502.0 nm = 3.95702156714741E-28 eV
[PhysicsDebug] 502.0 nm = 3.9570215671474107E-28 eV
[PhysicsDebug] 502.0 -> [0, 255, 123]
[PhysicsDebug] 650 -> [255, 0, 0]
[PhysicsDebug] 540 -> [129, 255, 0]
[PhysicsDebug] 470  -> [0, 169, 255]
[PhysicsDebug] 380nm to 780nm = 7625.7K to 3715.1K
[PhysicsDebug] 380nm 0.0K -> [97, 0, 97]
[PhysicsDebug] 780nm 0.0K -> [97, 0, 0]
[specrend] Temperature       x      y      z       R     G     B
[specrend] -----------    ------ ------ ------   ----- ----- -----
[specrend]    1000 K      0.6528 0.3444 0.0028   1.000 0.007 0.000 (Approximation)
[specrend]    1500 K      0.5857 0.3931 0.0212   1.000 0.126 0.000 (Approximation)
[specrend]    2000 K      0.5267 0.4133 0.0600   1.000 0.234 0.010
[specrend]    2500 K      0.4770 0.4137 0.1093   1.000 0.349 0.067
[specrend]    3000 K      0.4369 0.4041 0.1590   1.000 0.454 0.151
[specrend]    3500 K      0.4053 0.3907 0.2040   1.000 0.549 0.254
[specrend]    4000 K      0.3805 0.3768 0.2428   1.000 0.635 0.370
[specrend]    4500 K      0.3608 0.3636 0.2756   1.000 0.710 0.493
[specrend]    5000 K      0.3451 0.3516 0.3032   1.000 0.778 0.620
[specrend]    5500 K      0.3325 0.3411 0.3265   1.000 0.837 0.746
[specrend]    6000 K      0.3221 0.3318 0.3461   1.000 0.890 0.869
[specrend]    6500 K      0.3135 0.3237 0.3628   1.000 0.937 0.988
[specrend]    7000 K      0.3064 0.3166 0.3770   0.907 0.888 1.000
[specrend]    7500 K      0.3004 0.3103 0.3893   0.827 0.839 1.000
[specrend]    8000 K      0.2952 0.3048 0.4000   0.762 0.800 1.000
[specrend]    8500 K      0.2908 0.3000 0.4093   0.711 0.766 1.000
[specrend]    9000 K      0.2869 0.2956 0.4174   0.668 0.738 1.000
[specrend]    9500 K      0.2836 0.2918 0.4246   0.632 0.714 1.000
[specrend]   10000 K      0.2807 0.2884 0.4310   0.602 0.693 1.000
[PhysicsDebug]    5772 K      0.3266 0.3359 0.3376   1.000 0.867 0.813
[NoiseThreadPoolExecutor] Detected 20 available CPUs
[NoiseThreadPoolExecutor] Created ThreadPool with 10 threads
[MyMath] galaxy seed: 1

**Comment by 0XDE57** [comment]
hmm. this is normal debug output. its not showing the crash. ill see if I can figure out why the exception is not printed

**Comment by 0XDE57** [comment]
unable to repro
